<a href="https://colab.research.google.com/github/anuragpandey4/ml/blob/main/logistic_reg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import seaborn as sns
from sklearn. linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score

In [2]:
heart_df = pd.read_csv("heart.csv")
heart_df.sample(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
96,62,0,0,140,394,0,0,157,0,1.2,1,0,2,1
233,64,1,0,120,246,0,0,96,1,2.2,0,1,2,0
187,54,1,0,124,266,0,0,109,1,2.2,1,1,3,0
212,39,1,0,118,219,0,1,140,0,1.2,1,0,3,0
203,68,1,2,180,274,1,0,150,1,1.6,1,0,3,0

In [3]:
X = heart_df.drop(columns=["target"])
y = heart_df["target"]

In [4]:
#train test split

X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [5]:
y_train[y_train == 1] #133
y_train[y_train == 0] #109

202    0
196    0
176    0
177    0
258    0
      ..
257    0
214    0
302    0
188    0
270    0
Name: target, Length: 109, dtype: int64

In [6]:
model = LogisticRegression(max_iter = 10000)
model.fit(X_train,y_train)

LogisticRegression(max_iter=10000)

In [7]:
y_pred = model.predict(X_test)
y_pred

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [8]:
print("accuracy : ", accuracy_score(y_test,y_pred))

accuracy :  0.8852459016393442

In [9]:
print("precision : ", precision_score(y_test,y_pred))

precision :  0.8787878787878788